# Stage 1: Development
FROM node:18-alpine AS development

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./
COPY prisma ./prisma/

# Install all dependencies (including development dependencies)
RUN npm install

# Copy the rest of the application
COPY . .

RUN npm run build

FROM node:18-alpine

COPY --from=development /app/node_modules ./node_modules
COPY --from=development /app/package*.json ./
COPY --from=development /app/dist ./dist
COPY --from=development /app/prisma ./prisma

# Expose the port
EXPOSE 3001

# Command to run the application in development mode
CMD ["npm", "run", "start:migrate:dev"]